import random
class Progress:

    def __init__(self):
        self.funny_sayings = [
            "Making progress like a turtle on espresso.",
            "Slow and steady wins the race, but can we speed it up a bit?",
            "Turning caffeine into code, one cup at a time.",
            "Coding: where the only bugs are the ones in the software.",
            "Making the computer do my bidding, one keystroke at a time.",
            "Progress update: Not all who wander are lost, just debugging.",
            "Feeding my code some vitamins and debugging it on a treadmill.",
            "Code is like humor. When you have to explain it, it’s not that good.",
            "Dancing with algorithms and dodging syntax errors.",
            "Making progress faster than a cat video goes viral.",
            "Debugging is like being the detective in a crime movie where you are also the murderer.",
            "Life is too short for manual testing.",
            "I don't always test my code, but when I do, I do it in production.",
            "Why do programmers prefer dark mode? Less light, fewer bugs.",
            "The code works on my machine. Time to ship it!",
            "Trying to understand someone else's code is like trying to fold a fitted sheet.",
            "I'm not lazy; I'm on energy-saving mode.",
            "Real programmers count from 0.",
            "I'm not anti-social; I'm just not user-friendly.",
            "Code, coffee, sleep, repeat.",
            "I don't need a debugger; my code is perfect.",
            "In coding, the impossible is often the untried.",
            "I speak Python fluently.",
            "My code is like a fine wine; it gets better with age, but it also might have bugs.",
            "Don't interrupt someone debugging... unless you have chocolate.",
            "I don't always write unit tests, but when I do, I do it in production.",
            "I'm not a programmer; I just code a lot.",
            "Commitment issues? Have you tried version control?",
            "Why do programmers prefer dark mode? Less light, fewer bugs.",
            "I'm not lazy; I'm on energy-saving mode.",
            "Real programmers count from 0.",
            "I'm not anti-social; I'm just not user-friendly.",
            "Code, coffee, sleep, repeat.",
            "I don't need a debugger; my code is perfect.",
            "In coding, the impossible is often the untried.",
            "I speak Python fluently.",
            "My code is like a fine wine; it gets better with age, but it also might have bugs.",
            "Don't interrupt someone debugging... unless you have chocolate.",
            "I don't always write unit tests, but when I do, I do it in production.",
            "I'm not a programmer; I just code a lot.",
            "Commitment issues? Have you tried version control.",
            "Why do programmers prefer dark mode? Less light, fewer bugs.",
            "I'm not lazy; I'm on energy-saving mode.",
            "Real programmers count from 0.",
            "I'm not anti-social; I'm just not user-friendly.",
            "Code, coffee, sleep, repeat.",
            "I don't need a debugger; my code is perfect.",
            "In coding, the impossible is often the untried.",
            "I speak Python fluently.",
            "My code is like a fine wine; it gets better with age, but it also might have bugs.",
            "Don't interrupt someone debugging... unless you have chocolate.",
            "I don't always write unit tests, but when I do, I do it in production.",
            "I'm not a programmer; I just code a lot.",
            "Commitment issues? Have you tried version control.",
            "Why do programmers prefer dark mode? Less light, fewer bugs.",
            "I'm not lazy; I'm on energy-saving mode.",
            "Real programmers count from 0.",
            "I'm not anti-social; I'm just not user-friendly.",
            "Code, coffee, sleep, repeat.",
            "I don't need a debugger; my code is perfect.",
            "In coding, the impossible is often the untried.",
            "I speak Python fluently.",
            "My code is like a fine wine; it gets better with age, but it also might have bugs.",
            "Don't interrupt someone debugging... unless you have chocolate.",
            "I don't always write unit tests, but when I do, I do it in production.",
            "I'm not a programmer; I just code a lot.",
            "Commitment issues? Have you tried version control.",
            "Why do programmers prefer dark mode? Less light, fewer bugs.",
            "I'm not lazy; I'm on energy-saving mode.",
            "Real programmers count from 0.",
            "I'm not anti-social; I'm just not user-friendly.",
            "Code, coffee, sleep, repeat.",
            "I don't need a debugger; my code is perfect.",
            "In coding, the impossible is often the untried.",
            "I speak Python fluently.",
            "My code is like a fine wine; it gets better with age, but it also might have bugs.",
            "Don't interrupt someone debugging... unless you have chocolate.",
            "I don't always write unit tests, but when I do, I do it in production.",
            "I'm not a programmer; I just code a lot.",
            "Commitment issues? Have you tried version control.",
            "Why do programmers prefer dark mode? Less light, fewer bugs.",
            "I'm not lazy; I'm on energy-saving mode.",
            "Real programmers count from 0.",
            "I'm not anti-social; I'm just not user-friendly.",
            "Code, coffee, sleep, repeat.",
            "I don't need a debugger; my code is perfect.",
            "In coding, the impossible is often the untried.",
            "I speak Python fluently.",
            "My code is like a fine wine; it gets better with age, but it also might have bugs.",
            "Don't interrupt someone debugging... unless you have chocolate.",
            "I don't always write unit tests, but when I do, I do it in production.",
            "I'm not a programmer; I just code a lot.",
            "Commitment issues? Have you tried version control."
        ]
        self.saying = random.choice(self.funny_sayings)
    def update(self):
        self.saying = random.choice(self.funny_sayings)
        print("     " + self.saying)
        pass